### ISSUE TITLE
Error received when attempting to query location data

### ISSUE THREAD

**Issue by srevo** [WebBreacher/untappdScraper#9]
Receive the Following Error:

Traceback (most recent call last):
  File "./untappd.py", line 405, in <module>
    get_venue_data(args.user)
  File "./untappd.py", line 133, in get_venue_data
    venue1[2].replace('\t', '').replace('\n', ''), loc))
UnboundLocalError: local variable 'loc' referenced before assignment

**Comment by WebBreacher** [comment]
hi. thanks for using this tool. can you please give me some context? what version of python you using? what command did you run? did you get a google api and try to use that? The above error means little other than "this didn't work". It doesn't help me figure out why.

**Comment by srevo** [comment]
Hi, thanks for the reply. Here is some more information that I hope is helpful.

I am using VSCODE to run the code on OSX 10.15.2
I am running Python 3.7.6_1 and have the following modules installed 
bs4
geocoder
gmplot
googlemaps
requests
I have added my own API keys from Google and Bing to the geocode_api_keys.py. I have tested the API's in other applications and they appear to be valid. I also receive the same error in other OS and coding environments. 

the command I run: python3 untappd.py -u username

I get all the information [ ] USER DATA; [ ] FRIEND DATA: etc. When it gets to [ ] VENUE DATA: I receive the error I referenced above.

**Comment by WebBreacher** [comment]
Thanks for the info. Wondering...have you tried using a variety of usernames? Like, will the script run and complete successfully if you use the name `mogford` for the username? Asking because I've had issues in the past with international characters and the script. Wondering if it could be that.

**Comment by srevo** [comment]
I tried user **mogford** and various other users and unfortunately it yields the same error.

**Comment by WebBreacher** [comment]
Hmm. I just tried on several Ubuntu-based and Windows systems using Python 3.6.x and 3.8.x and had no issues with the script and the geocoding (which seems to be what your system is having trouble with). 

Couple of things to try as it appears the issue is either with the retrieving/parsing/calling to get the lat/long from Google:

1. revert the `geocode_api_keys.py` to the default `google_api_key = 'GOOGLE_API_KEY'` then rerun the script. If the venue data is pulled and displayed but not converted to lat/long, then we know the issue is somehow with Google API calls. I *just* used the script with the `mogford` account and successfully pulled all his data and resolved lat/long via Google. So I know it works and Google didn't change its API on me.
2. Make sure that your Google API key has not only the Geocoding API but also the Maps JavaScript API

Let me know what happens!

**Comment by srevo** [comment]
Enabling the **_Geocoding API_** did the trick. Thanks for your help and patience. 👍

**Comment by WebBreacher** [comment]
you got it!
